### ISSUE TITLE
Removing `uglify` task prevents JS output

### ISSUE THREAD

**Issue by markbates** [linemanjs/lineman-angular#5]
If you remove the `uglify` task:

``` js
removeTasks: {
  dist: ['uglify']
}
```

No JavaScript will be generated and placed into the `dist` folder.

**Comment by searls** [comment]
Clearly we've got some work cut out for us. I'm still convinced this is a
regression and that at some point this was working. I'm going to go rewind
to the pre-plugin-era to investigate.

Thanks for putting up with all the rough edges you're finding, wish your
ride to be smoother.

**Comment by searls** [comment]
Re: https://github.com/markbates/lineman-metacast/pull/1

Turns out uglify needs to be on, and ngmin has never been used as an outright replacement (just a preprocessor)

**Comment by mattbrewer** [comment]
Hello @searls and others!

I started using lineman in the past few weeks and I'm enjoying it!  The documentation is awesome!  I have been able to climb over all my issues, except **this** one... which is, sadly, **closed**. :(

It seems that uglification indeed breaks Angular.  When I run my rails embedded Angular app (which uses the rails-lineman gem and lineman-rails plugin) with my precompiled lineman assets, I receive the following:

`Uncaught Error: [$injector:unpr] Unknown provider: aProvider <- a`

From what I can tell from the folks that know more (you guys), ngmin **should be** a replacement for uglify.  Why doesn't the ngmin task just copy the generated app.js file into dist folder instead of depending on the uglify task to do so?

BTW, thanks for all you guys are doing to make lineman an awesome tool!

**Comment by mattbrewer** [comment]
Ok, after sleeping on it, I was able to see the light.  I added the following to application.js:

```
uglify: {
  options :
    {
      mangle: false
    }
}
```

Everything is good with the world.

**Comment by searls** [comment]
:)

**Comment by jasonkarns** [comment]
Hi @davemo do you have any input on this? Does uglify conflict with ngmin (if ngmin runs first)? Should we look into using ngmin _in place of_ uglify rather than _before_ uglify?

**Comment by davemo** [comment]
The only thing ngmin is responsible for is mapping the short form of Angular dependencies into the long form in your JavaScript code. https://github.com/btford/ngmin#tldr

However, ngmin assumes you are structuring your code in the recommended way for it to work. If you are using CoffeeScript, or other forms of defining modules and injecting dependencies YMMV with ngmin. 

FWIW, I've not had any problems using ngmin + uglify while leaving mangle on.
